services:
  postgres:
    image: postgres:15-alpine
    container_name: awesomepizza
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./database/config:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/postgresql/data
    restart: always